---
# tasks file for roles/web-app

- name: Run role Install Docker 
  include_role:
    name: docker

- name: Log into private registry and force re-authorization
  docker_login:
#    registry: teralex79/devops_exam
    username: teralex79
    password: gldpSi_2002
    reauthorize: yes

- name: pull an image
  docker_image:
    name: teralex79/devops_exam:latest 

- name: pull a test docker image
  docker_image: 
    name: hello-world    
