---
# tasks file for roles/web-app

- name: Run role Install Docker. 
  include_role:
    name: docker

- name: Login to dockerhub.
# and force re-authorization.
  docker_login:
    username: "{{ dockerhub_username }}" 
    password: "{{ dockerhub_password }}"  
#    reauthorize: yes

- name: Pull an image.
  docker_image:
    name: teralex79/devops_exam

- name: Run web container.
  docker_container:
    name: "{{ docker_name }}" 
    hostname: "{{ docker_name }}"
    ports:
      5001:5000
    image: teralex79/devops_exam
    state: started
    
